# Generated by Django 3.2.13 on 2022-05-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HCA_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('FAD', models.FloatField()),
                ('T_H_In', models.FloatField()),
                ('P_input', models.FloatField()),
                ('Q_input', models.FloatField()),
            ],
        ),
    ]
