# Generated by Django 3.2.13 on 2022-05-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERS', '0002_alter_hca_details_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('userID', models.CharField(default=None, max_length=100)),
                ('Email', models.EmailField(default=None, max_length=100)),
                ('Phone', models.CharField(default=None, max_length=100)),
                ('DOB', models.DateField()),
                ('password', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='hca_details',
            name='name',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
