# Generated by Django 3.2.13 on 2022-06-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERS', '0003_auto_20220530_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset_password_Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=200)),
                ('Aprove', models.IntegerField(default=0)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERS.users')),
            ],
        ),
        migrations.CreateModel(
            name='Registration_Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(default=None, max_length=100)),
                ('Aprove', models.IntegerField(default=1)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERS.users')),
            ],
        ),
    ]
