# Generated by Django 3.2.13 on 2022-06-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERS', '0004_registration_approval_reset_password_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_approval',
            name='UserID',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
