# Generated by Django 3.2.13 on 2022-06-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERS', '0005_alter_registration_approval_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CD26_airend_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_id', models.CharField(default=None, max_length=100)),
                ('P', models.FloatField()),
                ('p_S1', models.FloatField()),
                ('p_S2', models.FloatField()),
                ('FAD', models.FloatField()),
                ('Q_sh', models.FloatField()),
                ('Pr_ratio_stg1', models.FloatField()),
                ('Pr_ratio_stg2', models.FloatField()),
                ('n_stg1', models.FloatField()),
                ('n_stg2', models.FloatField()),
            ],
        ),
    ]
