# Generated by Django 3.2.13 on 2022-06-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERS', '0006_cd26_airend_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CD26_airend_data_rated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_id', models.CharField(default=None, max_length=100)),
                ('rated_P', models.FloatField()),
            ],
        ),
    ]
