# Generated by Django 3.2.13 on 2022-06-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERS', '0008_cd26_airend_data_rated_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reset_password_approval',
            name='UserID',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
