# Generated by Django 3.2.13 on 2022-06-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERS', '0009_alter_reset_password_approval_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd26_airend_data_rated',
            name='T_W_out',
            field=models.FloatField(default=0),
        ),
    ]
