# Generated by Django 3.2.13 on 2022-06-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERS', '0010_cd26_airend_data_rated_t_w_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_name', models.CharField(default=None, max_length=100)),
                ('H', models.FloatField(default=0)),
                ('t', models.FloatField(default=0)),
                ('lambda_2', models.FloatField(default=0)),
                ('OL', models.FloatField(default=0)),
                ('FinType', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
