# Generated by Django 3.2.13 on 2022-06-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERS', '0011_fin_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fin_details',
        ),
    ]
